export const GET_ALL_PLAYLISTS_LOADING = 'GET_ALL_PLAYLISTS_LOADING';
export const GET_ALL_PLAYLISTS_200 = 'GET_ALL_PLAYLISTS_200';
export const GET_ALL_PLAYLISTS_401 = 'GET_ALL_PLAYLISTS_401';
export const GET_ALL_PLAYLISTS_403 = 'GET_ALL_PLAYLISTS_403';
export const GET_ALL_PLAYLISTS_429 = 'GET_ALL_PLAYLISTS_429';
export const GET_ALL_PLAYLISTS_500 = 'GET_ALL_PLAYLISTS_500';

export const GET_PLAYLIST_ITEMS_LOADING = 'GET_PLAYLIST_ITEMS_LOADING';
export const GET_PLAYLIST_ITEMS_200 = 'GET_PLAYLIST_ITEMS_200';
export const GET_PLAYLIST_ITEMS_401 = 'GET_PLAYLIST_ITEMS_401';
export const GET_PLAYLIST_ITEMS_403 = 'GET_PLAYLIST_ITEMS_403';
export const GET_PLAYLIST_ITEMS_429 = 'GET_PLAYLIST_ITEMS_429';
export const GET_PLAYLIST_ITEMS_500 = 'GET_PLAYLIST_ITEMS_500';