export const GET_ALL_PLAYLISTS_LOADING = 'GET_ALL_PLAYLISTS_LOADING';
export const GET_ALL_PLAYLISTS_200 = 'GET_ALL_PLAYLISTS_200';
export const GET_ALL_PLAYLISTS_401 = 'GET_ALL_PLAYLISTS_401';
export const GET_ALL_PLAYLISTS_403 = 'GET_ALL_PLAYLISTS_403';
export const GET_ALL_PLAYLISTS_429 = 'GET_ALL_PLAYLISTS_429';
export const GET_ALL_PLAYLISTS_500 = 'GET_ALL_PLAYLISTS_500';