export const GET_YOUTUBE_RESULTS_LOADING = 'GET_YOUTUBE_RESULTS_LOADING';
export const GET_YOUTUBE_RESULTS_200 = 'GET_YOUTUBE_RESULTS_200';
export const GET_YOUTUBE_RESULTS_400 = 'GET_YOUTUBE_RESULTS_400';
export const GET_YOUTUBE_RESULTS_500 = 'GET_YOUTUBE_RESULTS_500';

export const ADD_VIDEO_200 = 'ADD_VIDEO_200';
export const ADD_VIDEO_500 = 'ADD_VIDEO_500';
export const ADD_VIDEO_REFRESH = 'ADD_VIDEO_REFRESH';

export const GET_VIDEOS_200 = 'GET_VIDEOS_200';
export const GET_VIDEOS_404 = 'GET_VIDEOS_404';
