export const GET_YOUTUBE_RESULTS_LOADING = 'GET_YOUTUBE_RESULTS_LOADING';
export const GET_YOUTUBE_RESULTS_200 = 'GET_YOUTUBE_RESULTS_200';
export const GET_YOUTUBE_RESULTS_400 = 'GET_YOUTUBE_RESULTS_400';
export const GET_YOUTUBE_RESULTS_500 = 'GET_YOUTUBE_RESULTS_500';
